apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot
    spec:
      containers:
      - image: 408595458482.dkr.ecr.us-east-1.amazonaws.com/juhi
        name: juhi
        resources: {}
status: {}
