apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot
  name: spring-boot
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot
  type: LoadBalancer
status:
  loadBalancer: {}
